package com.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2016-06-06T10:39:20.872+08:00
 * Generated source version: 2.7.16
 * 
 */
@WebServiceClient(name = "ProvinceCertClientService", 
                  wsdlLocation = "http://210.12.219.69/CertificateService/ProvinceCertClientService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ProvinceCertClientService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ProvinceCertClientService");
    public final static QName ProvinceCertClientServiceSoap = new QName("http://tempuri.org/", "ProvinceCertClientServiceSoap");
    public final static QName ProvinceCertClientServiceSoap12 = new QName("http://tempuri.org/", "ProvinceCertClientServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://210.12.219.69/CertificateService/ProvinceCertClientService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProvinceCertClientService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://210.12.219.69/CertificateService/ProvinceCertClientService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProvinceCertClientService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProvinceCertClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProvinceCertClientService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProvinceCertClientService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProvinceCertClientService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProvinceCertClientService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProvinceCertClientServiceSoap
     */
    @WebEndpoint(name = "ProvinceCertClientServiceSoap")
    public ProvinceCertClientServiceSoap getProvinceCertClientServiceSoap() {
        return super.getPort(ProvinceCertClientServiceSoap, ProvinceCertClientServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProvinceCertClientServiceSoap
     */
    @WebEndpoint(name = "ProvinceCertClientServiceSoap")
    public ProvinceCertClientServiceSoap getProvinceCertClientServiceSoap(WebServiceFeature... features) {
        return super.getPort(ProvinceCertClientServiceSoap, ProvinceCertClientServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ProvinceCertClientServiceSoap
     */
    @WebEndpoint(name = "ProvinceCertClientServiceSoap12")
    public ProvinceCertClientServiceSoap getProvinceCertClientServiceSoap12() {
        return super.getPort(ProvinceCertClientServiceSoap12, ProvinceCertClientServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProvinceCertClientServiceSoap
     */
    @WebEndpoint(name = "ProvinceCertClientServiceSoap12")
    public ProvinceCertClientServiceSoap getProvinceCertClientServiceSoap12(WebServiceFeature... features) {
        return super.getPort(ProvinceCertClientServiceSoap12, ProvinceCertClientServiceSoap.class, features);
    }

}
