
package com.webservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2016-06-06T10:39:20.778+08:00
 * Generated source version: 2.7.16
 * 
 */
public final class ProvinceCertClientServiceSoap_ProvinceCertClientServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "ProvinceCertClientService");

    private ProvinceCertClientServiceSoap_ProvinceCertClientServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProvinceCertClientService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProvinceCertClientService ss = new ProvinceCertClientService(wsdlURL, SERVICE_NAME);
        ProvinceCertClientServiceSoap port = ss.getProvinceCertClientServiceSoap12();  
        
        {
        System.out.println("Invoking readOldShiGongCertInfo...");
        java.lang.String _readOldShiGongCertInfo_strUserName = "";
        java.lang.String _readOldShiGongCertInfo_strPwd = "";
        javax.xml.ws.Holder<java.lang.String> _readOldShiGongCertInfo_readOldShiGongCertInfoResult = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _readOldShiGongCertInfo_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.readOldShiGongCertInfo(_readOldShiGongCertInfo_strUserName, _readOldShiGongCertInfo_strPwd, _readOldShiGongCertInfo_readOldShiGongCertInfoResult, _readOldShiGongCertInfo_strErrMsg);

        System.out.println("readOldShiGongCertInfo._readOldShiGongCertInfo_readOldShiGongCertInfoResult=" + _readOldShiGongCertInfo_readOldShiGongCertInfoResult.value);
        System.out.println("readOldShiGongCertInfo._readOldShiGongCertInfo_strErrMsg=" + _readOldShiGongCertInfo_strErrMsg.value);

        }
        {
        System.out.println("Invoking logoutCertInfo...");
        java.lang.String _logoutCertInfo_strUserName = "";
        java.lang.String _logoutCertInfo_strPwd = "";
        java.lang.String _logoutCertInfo_strCertTypeNum = "";
        java.lang.String _logoutCertInfo_strCertID = "";
        java.lang.String _logoutCertInfo_strLogOutMark = "";
        javax.xml.ws.Holder<java.lang.Boolean> _logoutCertInfo_logoutCertInfoResult = new javax.xml.ws.Holder<java.lang.Boolean>();
        javax.xml.ws.Holder<java.lang.String> _logoutCertInfo_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.logoutCertInfo(_logoutCertInfo_strUserName, _logoutCertInfo_strPwd, _logoutCertInfo_strCertTypeNum, _logoutCertInfo_strCertID, _logoutCertInfo_strLogOutMark, _logoutCertInfo_logoutCertInfoResult, _logoutCertInfo_strErrMsg);

        System.out.println("logoutCertInfo._logoutCertInfo_logoutCertInfoResult=" + _logoutCertInfo_logoutCertInfoResult.value);
        System.out.println("logoutCertInfo._logoutCertInfo_strErrMsg=" + _logoutCertInfo_strErrMsg.value);

        }
        {
        System.out.println("Invoking updateOldShiGongModifyInfo...");
        java.lang.String _updateOldShiGongModifyInfo_strUserName = "";
        java.lang.String _updateOldShiGongModifyInfo_strPwd = "";
        java.lang.String _updateOldShiGongModifyInfo_strCertNum = "";
        java.lang.String _updateOldShiGongModifyInfo_strCertID = "";
        java.lang.String _updateOldShiGongModifyInfo_strCorpXml = "";
        javax.xml.ws.Holder<java.lang.Boolean> _updateOldShiGongModifyInfo_updateOldShiGongModifyInfoResult = new javax.xml.ws.Holder<java.lang.Boolean>();
        javax.xml.ws.Holder<java.lang.String> _updateOldShiGongModifyInfo_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.updateOldShiGongModifyInfo(_updateOldShiGongModifyInfo_strUserName, _updateOldShiGongModifyInfo_strPwd, _updateOldShiGongModifyInfo_strCertNum, _updateOldShiGongModifyInfo_strCertID, _updateOldShiGongModifyInfo_strCorpXml, _updateOldShiGongModifyInfo_updateOldShiGongModifyInfoResult, _updateOldShiGongModifyInfo_strErrMsg);

        System.out.println("updateOldShiGongModifyInfo._updateOldShiGongModifyInfo_updateOldShiGongModifyInfoResult=" + _updateOldShiGongModifyInfo_updateOldShiGongModifyInfoResult.value);
        System.out.println("updateOldShiGongModifyInfo._updateOldShiGongModifyInfo_strErrMsg=" + _updateOldShiGongModifyInfo_strErrMsg.value);

        }
        {
        System.out.println("Invoking testOldShiGongCertSlbIsExists...");
        java.lang.String _testOldShiGongCertSlbIsExists_strUserName = "";
        java.lang.String _testOldShiGongCertSlbIsExists_strPwd = "";
        java.lang.String _testOldShiGongCertSlbIsExists_strCorpName = "";
        java.lang.String _testOldShiGongCertSlbIsExists_strCertID = "";
        javax.xml.ws.Holder<java.lang.Integer> _testOldShiGongCertSlbIsExists_testOldShiGongCertSlbIsExistsResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _testOldShiGongCertSlbIsExists_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.testOldShiGongCertSlbIsExists(_testOldShiGongCertSlbIsExists_strUserName, _testOldShiGongCertSlbIsExists_strPwd, _testOldShiGongCertSlbIsExists_strCorpName, _testOldShiGongCertSlbIsExists_strCertID, _testOldShiGongCertSlbIsExists_testOldShiGongCertSlbIsExistsResult, _testOldShiGongCertSlbIsExists_strErrMsg);

        System.out.println("testOldShiGongCertSlbIsExists._testOldShiGongCertSlbIsExists_testOldShiGongCertSlbIsExistsResult=" + _testOldShiGongCertSlbIsExists_testOldShiGongCertSlbIsExistsResult.value);
        System.out.println("testOldShiGongCertSlbIsExists._testOldShiGongCertSlbIsExists_strErrMsg=" + _testOldShiGongCertSlbIsExists_strErrMsg.value);

        }
        {
        System.out.println("Invoking helloWorld...");
        java.lang.String _helloWorld__return = port.helloWorld();
        System.out.println("helloWorld.result=" + _helloWorld__return);


        }
        {
        System.out.println("Invoking uploadCertInfoNotPrint...");
        java.lang.String _uploadCertInfoNotPrint_strCertTypeNum = "";
        java.lang.String _uploadCertInfoNotPrint_strUserName = "";
        java.lang.String _uploadCertInfoNotPrint_strPwd = "";
        java.lang.String _uploadCertInfoNotPrint_strCertXml = "";
        javax.xml.ws.Holder<java.lang.Integer> _uploadCertInfoNotPrint_uploadCertInfoNotPrintResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _uploadCertInfoNotPrint_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.uploadCertInfoNotPrint(_uploadCertInfoNotPrint_strCertTypeNum, _uploadCertInfoNotPrint_strUserName, _uploadCertInfoNotPrint_strPwd, _uploadCertInfoNotPrint_strCertXml, _uploadCertInfoNotPrint_uploadCertInfoNotPrintResult, _uploadCertInfoNotPrint_strErrMsg);

        System.out.println("uploadCertInfoNotPrint._uploadCertInfoNotPrint_uploadCertInfoNotPrintResult=" + _uploadCertInfoNotPrint_uploadCertInfoNotPrintResult.value);
        System.out.println("uploadCertInfoNotPrint._uploadCertInfoNotPrint_strErrMsg=" + _uploadCertInfoNotPrint_strErrMsg.value);

        }
        {
        System.out.println("Invoking uploadOldShiGongCertInfo...");
        java.lang.String _uploadOldShiGongCertInfo_strUserName = "";
        java.lang.String _uploadOldShiGongCertInfo_strPwd = "";
        java.lang.String _uploadOldShiGongCertInfo_strCertXml = "";
        javax.xml.ws.Holder<java.lang.Integer> _uploadOldShiGongCertInfo_uploadOldShiGongCertInfoResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _uploadOldShiGongCertInfo_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.uploadOldShiGongCertInfo(_uploadOldShiGongCertInfo_strUserName, _uploadOldShiGongCertInfo_strPwd, _uploadOldShiGongCertInfo_strCertXml, _uploadOldShiGongCertInfo_uploadOldShiGongCertInfoResult, _uploadOldShiGongCertInfo_strErrMsg);

        System.out.println("uploadOldShiGongCertInfo._uploadOldShiGongCertInfo_uploadOldShiGongCertInfoResult=" + _uploadOldShiGongCertInfo_uploadOldShiGongCertInfoResult.value);
        System.out.println("uploadOldShiGongCertInfo._uploadOldShiGongCertInfo_strErrMsg=" + _uploadOldShiGongCertInfo_strErrMsg.value);

        }
        {
        System.out.println("Invoking readOldShiGongCertInfoDetails...");
        java.lang.String _readOldShiGongCertInfoDetails_strUserName = "";
        java.lang.String _readOldShiGongCertInfoDetails_strPwd = "";
        java.lang.String _readOldShiGongCertInfoDetails_strCertNum = "";
        javax.xml.ws.Holder<java.lang.String> _readOldShiGongCertInfoDetails_readOldShiGongCertInfoDetailsResult = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _readOldShiGongCertInfoDetails_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.readOldShiGongCertInfoDetails(_readOldShiGongCertInfoDetails_strUserName, _readOldShiGongCertInfoDetails_strPwd, _readOldShiGongCertInfoDetails_strCertNum, _readOldShiGongCertInfoDetails_readOldShiGongCertInfoDetailsResult, _readOldShiGongCertInfoDetails_strErrMsg);

        System.out.println("readOldShiGongCertInfoDetails._readOldShiGongCertInfoDetails_readOldShiGongCertInfoDetailsResult=" + _readOldShiGongCertInfoDetails_readOldShiGongCertInfoDetailsResult.value);
        System.out.println("readOldShiGongCertInfoDetails._readOldShiGongCertInfoDetails_strErrMsg=" + _readOldShiGongCertInfoDetails_strErrMsg.value);

        }
        {
        System.out.println("Invoking uploadJSCertAddressInfo...");
        java.lang.String _uploadJSCertAddressInfo_strUserName = "";
        java.lang.String _uploadJSCertAddressInfo_strPwd = "";
        java.lang.String _uploadJSCertAddressInfo_strCorpXml = "";
        javax.xml.ws.Holder<java.lang.Integer> _uploadJSCertAddressInfo_uploadJSCertAddressInfoResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _uploadJSCertAddressInfo_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.uploadJSCertAddressInfo(_uploadJSCertAddressInfo_strUserName, _uploadJSCertAddressInfo_strPwd, _uploadJSCertAddressInfo_strCorpXml, _uploadJSCertAddressInfo_uploadJSCertAddressInfoResult, _uploadJSCertAddressInfo_strErrMsg);

        System.out.println("uploadJSCertAddressInfo._uploadJSCertAddressInfo_uploadJSCertAddressInfoResult=" + _uploadJSCertAddressInfo_uploadJSCertAddressInfoResult.value);
        System.out.println("uploadJSCertAddressInfo._uploadJSCertAddressInfo_strErrMsg=" + _uploadJSCertAddressInfo_strErrMsg.value);

        }
        {
        System.out.println("Invoking logoutOldShiGongCertInfo...");
        java.lang.String _logoutOldShiGongCertInfo_strUserName = "";
        java.lang.String _logoutOldShiGongCertInfo_strPwd = "";
        java.lang.String _logoutOldShiGongCertInfo_strCertNum = "";
        java.lang.String _logoutOldShiGongCertInfo_strLogOutMark = "";
        javax.xml.ws.Holder<java.lang.Boolean> _logoutOldShiGongCertInfo_logoutOldShiGongCertInfoResult = new javax.xml.ws.Holder<java.lang.Boolean>();
        javax.xml.ws.Holder<java.lang.String> _logoutOldShiGongCertInfo_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.logoutOldShiGongCertInfo(_logoutOldShiGongCertInfo_strUserName, _logoutOldShiGongCertInfo_strPwd, _logoutOldShiGongCertInfo_strCertNum, _logoutOldShiGongCertInfo_strLogOutMark, _logoutOldShiGongCertInfo_logoutOldShiGongCertInfoResult, _logoutOldShiGongCertInfo_strErrMsg);

        System.out.println("logoutOldShiGongCertInfo._logoutOldShiGongCertInfo_logoutOldShiGongCertInfoResult=" + _logoutOldShiGongCertInfo_logoutOldShiGongCertInfoResult.value);
        System.out.println("logoutOldShiGongCertInfo._logoutOldShiGongCertInfo_strErrMsg=" + _logoutOldShiGongCertInfo_strErrMsg.value);

        }
        {
        System.out.println("Invoking updateOldShiGongModifyInfo2...");
        java.lang.String _updateOldShiGongModifyInfo2_strUserName = "";
        java.lang.String _updateOldShiGongModifyInfo2_strPwd = "";
        java.lang.String _updateOldShiGongModifyInfo2_strCorpName = "";
        java.lang.String _updateOldShiGongModifyInfo2_strCorpCode = "";
        java.lang.String _updateOldShiGongModifyInfo2_strCertID = "";
        java.lang.String _updateOldShiGongModifyInfo2_strCorpXml = "";
        javax.xml.ws.Holder<java.lang.Boolean> _updateOldShiGongModifyInfo2_updateOldShiGongModifyInfo2Result = new javax.xml.ws.Holder<java.lang.Boolean>();
        javax.xml.ws.Holder<java.lang.String> _updateOldShiGongModifyInfo2_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.updateOldShiGongModifyInfo2(_updateOldShiGongModifyInfo2_strUserName, _updateOldShiGongModifyInfo2_strPwd, _updateOldShiGongModifyInfo2_strCorpName, _updateOldShiGongModifyInfo2_strCorpCode, _updateOldShiGongModifyInfo2_strCertID, _updateOldShiGongModifyInfo2_strCorpXml, _updateOldShiGongModifyInfo2_updateOldShiGongModifyInfo2Result, _updateOldShiGongModifyInfo2_strErrMsg);

        System.out.println("updateOldShiGongModifyInfo2._updateOldShiGongModifyInfo2_updateOldShiGongModifyInfo2Result=" + _updateOldShiGongModifyInfo2_updateOldShiGongModifyInfo2Result.value);
        System.out.println("updateOldShiGongModifyInfo2._updateOldShiGongModifyInfo2_strErrMsg=" + _updateOldShiGongModifyInfo2_strErrMsg.value);

        }
        {
        System.out.println("Invoking logoutCertInfo2...");
        java.lang.String _logoutCertInfo2_strUserName = "";
        java.lang.String _logoutCertInfo2_strPwd = "";
        java.lang.String _logoutCertInfo2_strCertTypeNum = "";
        java.lang.String _logoutCertInfo2_strCorpName = "";
        java.lang.String _logoutCertInfo2_strCertID = "";
        java.lang.String _logoutCertInfo2_strLogOutMark = "";
        javax.xml.ws.Holder<java.lang.Boolean> _logoutCertInfo2_logoutCertInfo2Result = new javax.xml.ws.Holder<java.lang.Boolean>();
        javax.xml.ws.Holder<java.lang.String> _logoutCertInfo2_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.logoutCertInfo2(_logoutCertInfo2_strUserName, _logoutCertInfo2_strPwd, _logoutCertInfo2_strCertTypeNum, _logoutCertInfo2_strCorpName, _logoutCertInfo2_strCertID, _logoutCertInfo2_strLogOutMark, _logoutCertInfo2_logoutCertInfo2Result, _logoutCertInfo2_strErrMsg);

        System.out.println("logoutCertInfo2._logoutCertInfo2_logoutCertInfo2Result=" + _logoutCertInfo2_logoutCertInfo2Result.value);
        System.out.println("logoutCertInfo2._logoutCertInfo2_strErrMsg=" + _logoutCertInfo2_strErrMsg.value);

        }
        {
        System.out.println("Invoking uploadCertInfo...");
        java.lang.String _uploadCertInfo_strCertTypeNum = "";
        java.lang.String _uploadCertInfo_strUserName = "";
        java.lang.String _uploadCertInfo_strPwd = "";
        java.lang.String _uploadCertInfo_strCertXml = "";
        javax.xml.ws.Holder<java.lang.Integer> _uploadCertInfo_uploadCertInfoResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _uploadCertInfo_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.uploadCertInfo(_uploadCertInfo_strCertTypeNum, _uploadCertInfo_strUserName, _uploadCertInfo_strPwd, _uploadCertInfo_strCertXml, _uploadCertInfo_uploadCertInfoResult, _uploadCertInfo_strErrMsg);

        System.out.println("uploadCertInfo._uploadCertInfo_uploadCertInfoResult=" + _uploadCertInfo_uploadCertInfoResult.value);
        System.out.println("uploadCertInfo._uploadCertInfo_strErrMsg=" + _uploadCertInfo_strErrMsg.value);

        }
        {
        System.out.println("Invoking uploadSheJiCertInfo...");
        java.lang.String _uploadSheJiCertInfo_strCertTypeNum = "";
        java.lang.String _uploadSheJiCertInfo_strUserName = "";
        java.lang.String _uploadSheJiCertInfo_strPwd = "";
        java.lang.String _uploadSheJiCertInfo_strCertXml = "";
        javax.xml.ws.Holder<java.lang.Integer> _uploadSheJiCertInfo_uploadSheJiCertInfoResult = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _uploadSheJiCertInfo_strErrMsg = new javax.xml.ws.Holder<java.lang.String>();
        port.uploadSheJiCertInfo(_uploadSheJiCertInfo_strCertTypeNum, _uploadSheJiCertInfo_strUserName, _uploadSheJiCertInfo_strPwd, _uploadSheJiCertInfo_strCertXml, _uploadSheJiCertInfo_uploadSheJiCertInfoResult, _uploadSheJiCertInfo_strErrMsg);

        System.out.println("uploadSheJiCertInfo._uploadSheJiCertInfo_uploadSheJiCertInfoResult=" + _uploadSheJiCertInfo_uploadSheJiCertInfoResult.value);
        System.out.println("uploadSheJiCertInfo._uploadSheJiCertInfo_strErrMsg=" + _uploadSheJiCertInfo_strErrMsg.value);

        }

        System.exit(0);
    }

}
