package com.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2016-06-06T10:39:20.841+08:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ProvinceCertClientServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ProvinceCertClientServiceSoap {

    /**
     * 读取旧的施工类证书的信息
     */
    @RequestWrapper(localName = "ReadOldShiGongCertInfo", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.ReadOldShiGongCertInfo")
    @WebMethod(operationName = "ReadOldShiGongCertInfo", action = "http://tempuri.org/ReadOldShiGongCertInfo")
    @ResponseWrapper(localName = "ReadOldShiGongCertInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.ReadOldShiGongCertInfoResponse")
    public void readOldShiGongCertInfo(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(mode = WebParam.Mode.OUT, name = "ReadOldShiGongCertInfoResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> readOldShiGongCertInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 注销某个证书信息
     */
    @RequestWrapper(localName = "LogoutCertInfo", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.LogoutCertInfo")
    @WebMethod(operationName = "LogoutCertInfo", action = "http://tempuri.org/LogoutCertInfo")
    @ResponseWrapper(localName = "LogoutCertInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.LogoutCertInfoResponse")
    public void logoutCertInfo(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCertTypeNum", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertTypeNum,
        @WebParam(name = "strCertID", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertID,
        @WebParam(name = "strLogOutMark", targetNamespace = "http://tempuri.org/")
        java.lang.String strLogOutMark,
        @WebParam(mode = WebParam.Mode.OUT, name = "LogoutCertInfoResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> logoutCertInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 更新部级证书的变更信息
     */
    @RequestWrapper(localName = "UpdateOldShiGongModifyInfo", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UpdateOldShiGongModifyInfo")
    @WebMethod(operationName = "UpdateOldShiGongModifyInfo", action = "http://tempuri.org/UpdateOldShiGongModifyInfo")
    @ResponseWrapper(localName = "UpdateOldShiGongModifyInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UpdateOldShiGongModifyInfoResponse")
    public void updateOldShiGongModifyInfo(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCertNum", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertNum,
        @WebParam(name = "strCertID", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertID,
        @WebParam(name = "strCorpXml", targetNamespace = "http://tempuri.org/")
        java.lang.String strCorpXml,
        @WebParam(mode = WebParam.Mode.OUT, name = "UpdateOldShiGongModifyInfoResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> updateOldShiGongModifyInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 检查旧的施工类证书是否属于受理办核发的资质证书
     */
    @RequestWrapper(localName = "TestOldShiGongCertSlbIsExists", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.TestOldShiGongCertSlbIsExists")
    @WebMethod(operationName = "TestOldShiGongCertSlbIsExists", action = "http://tempuri.org/TestOldShiGongCertSlbIsExists")
    @ResponseWrapper(localName = "TestOldShiGongCertSlbIsExistsResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.TestOldShiGongCertSlbIsExistsResponse")
    public void testOldShiGongCertSlbIsExists(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCorpName", targetNamespace = "http://tempuri.org/")
        java.lang.String strCorpName,
        @WebParam(name = "strCertID", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertID,
        @WebParam(mode = WebParam.Mode.OUT, name = "TestOldShiGongCertSlbIsExistsResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Integer> testOldShiGongCertSlbIsExistsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.HelloWorldResponse")
    public java.lang.String helloWorld();

    /**
     * 上报证书基本信息
     */
    @RequestWrapper(localName = "UploadCertInfoNotPrint", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadCertInfoNotPrint")
    @WebMethod(operationName = "UploadCertInfoNotPrint", action = "http://tempuri.org/UploadCertInfoNotPrint")
    @ResponseWrapper(localName = "UploadCertInfoNotPrintResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadCertInfoNotPrintResponse")
    public void uploadCertInfoNotPrint(
        @WebParam(name = "strCertTypeNum", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertTypeNum,
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCertXml", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertXml,
        @WebParam(mode = WebParam.Mode.OUT, name = "UploadCertInfoNotPrintResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Integer> uploadCertInfoNotPrintResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 上报旧的施工类证书基本信息
     */
    @RequestWrapper(localName = "UploadOldShiGongCertInfo", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadOldShiGongCertInfo")
    @WebMethod(operationName = "UploadOldShiGongCertInfo", action = "http://tempuri.org/UploadOldShiGongCertInfo")
    @ResponseWrapper(localName = "UploadOldShiGongCertInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadOldShiGongCertInfoResponse")
    public void uploadOldShiGongCertInfo(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCertXml", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertXml,
        @WebParam(mode = WebParam.Mode.OUT, name = "UploadOldShiGongCertInfoResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Integer> uploadOldShiGongCertInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 读取旧的施工类证书的信息
     */
    @RequestWrapper(localName = "ReadOldShiGongCertInfoDetails", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.ReadOldShiGongCertInfoDetails")
    @WebMethod(operationName = "ReadOldShiGongCertInfoDetails", action = "http://tempuri.org/ReadOldShiGongCertInfoDetails")
    @ResponseWrapper(localName = "ReadOldShiGongCertInfoDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.ReadOldShiGongCertInfoDetailsResponse")
    public void readOldShiGongCertInfoDetails(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCertNum", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "ReadOldShiGongCertInfoDetailsResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> readOldShiGongCertInfoDetailsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 更新地址信息
     */
    @RequestWrapper(localName = "UploadJSCertAddressInfo", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadJSCertAddressInfo")
    @WebMethod(operationName = "UploadJSCertAddressInfo", action = "http://tempuri.org/UploadJSCertAddressInfo")
    @ResponseWrapper(localName = "UploadJSCertAddressInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadJSCertAddressInfoResponse")
    public void uploadJSCertAddressInfo(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCorpXml", targetNamespace = "http://tempuri.org/")
        java.lang.String strCorpXml,
        @WebParam(mode = WebParam.Mode.OUT, name = "UploadJSCertAddressInfoResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Integer> uploadJSCertAddressInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 注销某个证书信息
     */
    @RequestWrapper(localName = "LogoutOldShiGongCertInfo", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.LogoutOldShiGongCertInfo")
    @WebMethod(operationName = "LogoutOldShiGongCertInfo", action = "http://tempuri.org/LogoutOldShiGongCertInfo")
    @ResponseWrapper(localName = "LogoutOldShiGongCertInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.LogoutOldShiGongCertInfoResponse")
    public void logoutOldShiGongCertInfo(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCertNum", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertNum,
        @WebParam(name = "strLogOutMark", targetNamespace = "http://tempuri.org/")
        java.lang.String strLogOutMark,
        @WebParam(mode = WebParam.Mode.OUT, name = "LogoutOldShiGongCertInfoResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> logoutOldShiGongCertInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 更新部级证书的变更信息
     */
    @RequestWrapper(localName = "UpdateOldShiGongModifyInfo2", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UpdateOldShiGongModifyInfo2")
    @WebMethod(operationName = "UpdateOldShiGongModifyInfo2", action = "http://tempuri.org/UpdateOldShiGongModifyInfo2")
    @ResponseWrapper(localName = "UpdateOldShiGongModifyInfo2Response", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UpdateOldShiGongModifyInfo2Response")
    public void updateOldShiGongModifyInfo2(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCorpName", targetNamespace = "http://tempuri.org/")
        java.lang.String strCorpName,
        @WebParam(name = "strCorpCode", targetNamespace = "http://tempuri.org/")
        java.lang.String strCorpCode,
        @WebParam(name = "strCertID", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertID,
        @WebParam(name = "strCorpXml", targetNamespace = "http://tempuri.org/")
        java.lang.String strCorpXml,
        @WebParam(mode = WebParam.Mode.OUT, name = "UpdateOldShiGongModifyInfo2Result", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> updateOldShiGongModifyInfo2Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 注销某个证书信息
     */
    @RequestWrapper(localName = "LogoutCertInfo2", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.LogoutCertInfo2")
    @WebMethod(operationName = "LogoutCertInfo2", action = "http://tempuri.org/LogoutCertInfo2")
    @ResponseWrapper(localName = "LogoutCertInfo2Response", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.LogoutCertInfo2Response")
    public void logoutCertInfo2(
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCertTypeNum", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertTypeNum,
        @WebParam(name = "strCorpName", targetNamespace = "http://tempuri.org/")
        java.lang.String strCorpName,
        @WebParam(name = "strCertID", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertID,
        @WebParam(name = "strLogOutMark", targetNamespace = "http://tempuri.org/")
        java.lang.String strLogOutMark,
        @WebParam(mode = WebParam.Mode.OUT, name = "LogoutCertInfo2Result", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> logoutCertInfo2Result,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 上报证书基本信息
     */
    @RequestWrapper(localName = "UploadCertInfo", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadCertInfo")
    @WebMethod(operationName = "UploadCertInfo", action = "http://tempuri.org/UploadCertInfo")
    @ResponseWrapper(localName = "UploadCertInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadCertInfoResponse")
    public void uploadCertInfo(
        @WebParam(name = "strCertTypeNum", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertTypeNum,
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCertXml", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertXml,
        @WebParam(mode = WebParam.Mode.OUT, name = "UploadCertInfoResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Integer> uploadCertInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );

    /**
     * 上报证书基本信息
     */
    @RequestWrapper(localName = "UploadSheJiCertInfo", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadSheJiCertInfo")
    @WebMethod(operationName = "UploadSheJiCertInfo", action = "http://tempuri.org/UploadSheJiCertInfo")
    @ResponseWrapper(localName = "UploadSheJiCertInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.UploadSheJiCertInfoResponse")
    public void uploadSheJiCertInfo(
        @WebParam(name = "strCertTypeNum", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertTypeNum,
        @WebParam(name = "strUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserName,
        @WebParam(name = "strPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strPwd,
        @WebParam(name = "strCertXml", targetNamespace = "http://tempuri.org/")
        java.lang.String strCertXml,
        @WebParam(mode = WebParam.Mode.OUT, name = "UploadSheJiCertInfoResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Integer> uploadSheJiCertInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "strErrMsg", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> strErrMsg
    );
}
