
package com.webservice.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2016-06-06T10:39:20.856+08:00
 * Generated source version: 2.7.16
 * 
 */
 
public class ProvinceCertClientServiceSoap_ProvinceCertClientServiceSoap_Server{

    protected ProvinceCertClientServiceSoap_ProvinceCertClientServiceSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ProvinceCertClientServiceSoapImpl();
        String address = "http://210.12.219.69/CertificateService/ProvinceCertClientService.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ProvinceCertClientServiceSoap_ProvinceCertClientServiceSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
